const datos = [
  {
    causalidad: 'Papel Mal cargado, papel no adecuado o impresora sin papel',
    tipoSR: 'CHGC',
    codigoEntorno: '19KM',
    codigoReparacion: '14',
    categoria: '1B',
    mayor: '7C',
    menor: 'S5',
    description: 'Out of Paper / Consumables',
    comentario: 'Si es reporte de FLM se cierra CHGF'
  },
  {
    causalidad: 'Reseteo ATM',
    tipoSR: 'CHGC',
    codigoEntorno: '19NR',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: '50',
    menor: 'XB',
    description: 'Other See Comments',
    comentario: 'Si es reporte de FLM se cierra CHGF'
  },
  {
    causalidad: 'Bajar Auditoria,  Log de errores, Silent Debug, configuracion por solicitud del cliente o de NCR',
    tipoSR: 'CHGC',
    codigoEntorno: '19KI',
    codigoReparacion: '34',
    categoria: '1B',
    mayor: '50',
    menor: '1O',
    description: 'Electronic Journal Full',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Cliente solicita Ingreso Llaves de Encripcion ',
    tipoSR: 'CHGC',
    codigoEntorno: '19KA',
    codigoReparacion: '59',
    categoria: '1B',
    mayor: 'ED',
    menor: 'SI',
    description: 'Des Keys Request',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Cliente solicita Autenticar dispensador x Cambio Software',
    tipoSR: 'CHGC',
    codigoEntorno: '19KP',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: 'CH',
    menor: 'X1',
    description: 'Non-Ncr Sw / Hw Error',
    comentario: ' '
  },
  {
    causalidad: 'Error Operativo - ATM Apagado por reparacion Boveda - Site - PM programado',
    tipoSR: 'CHGC',
    codigoEntorno: '19K4',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: '36',
    menor: 'ZU',
    description: 'Bad/No Power or ATM',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Error Operativo - ATM en Supervisor',
    tipoSR: 'CHGC',
    codigoEntorno: '19NR',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: '50',
    menor: 'XB',
    description: 'Other See Comments',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Error Operativo - Cable dispensador suelto',
    tipoSR: 'CHGC',
    codigoEntorno: '19K4',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: 'ND',
    menor: 'J7',
    description: 'Bad/No Power or ATM',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Error Operativo - Cable Potencia desconectado',
    tipoSR: 'CHGC',
    codigoEntorno: '19K4',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: '36',
    menor: 'ZU',
    description: 'Bad/No Power or ATM',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Error Operativo - Dinero en mal estado (tomar fotos) Provisionado o generando atascos ',
    tipoSR: 'CHGC',
    codigoEntorno: '19K7',
    codigoReparacion: '03',
    categoria: '1B',
    mayor: '',
    menor: '',
    description: 'Dispense Cash Quality / Load',
    comentario: ''
  },
  {
    causalidad: 'Error Operativo - Dispositivo interno desconectado',
    tipoSR: 'CHGC',
    codigoEntorno: '19KB',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: 'CH',
    menor: 'J7',
    description: 'End User / Operator Error',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Error Operativo - Fajilla de billetes obstruia sensor',
    tipoSR: 'CHGC',
    codigoEntorno: '19K7',
    codigoReparacion: 'O3',
    categoria: '1B',
    mayor: 'ND',
    menor: 'BL',
    description: 'Dispense Cash Quality / Load',
    comentario: ' '
  },
  {
    causalidad: 'Error Operativo - Gaveta sin dinero ',
    tipoSR: 'CHGC',
    codigoEntorno: '19K5',
    codigoReparacion: '59',
    categoria: '1B',
    mayor: '74',
    menor: 'Q2',
    description: 'Cash Out / Cash Low',
    comentario: ' '
  },
  {
    causalidad: 'Error Operativo - Gavetas BNA llenas de dinero obstruyendo sensor',
    tipoSR: 'CHGC',
    codigoEntorno: '19KE',
    codigoReparacion: '59',
    categoria: '1B',
    mayor: 'ND',
    menor: 'BL',
    description: 'Check / Cash / Purge Bin Full',
    comentario: ' '
  },
  {
    causalidad: 'Error Operativo - Mal enrutado el cable comunicaciones o suelto',
    tipoSR: 'CHGC',
    codigoEntorno: '19K9',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: 'PN',
    menor: 'D4',
    description: 'Customer Wiring',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Error Operativo - No hay ATM en sitio',
    tipoSR: 'CHGC',
    codigoEntorno: '19NR',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: '50',
    menor: 'XB',
    description: 'Other See Comments',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Error Operativo - Inactividad ATM',
    tipoSR: 'CHGC',
    codigoEntorno: '19KR',
    codigoReparacion: '53',
    categoria: '1B',
    mayor: '36',
    menor: 'W3',
    description: 'No Fault Found (Nff)',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Error Operativo - TDV mal engachada gaveta',
    tipoSR: 'CHGC',
    codigoEntorno: '19K6',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: 'ND',
    menor: 'CC',
    description: 'Cassettes Not Seated',
    comentario: ' '
  },
  {
    causalidad: 'Error Operativo - TDV manipulacion escrow',
    tipoSR: 'CHGC',
    codigoEntorno: '19NS',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: '2C',
    menor: 'F5',
    description: 'Replenisher Improper Operation /Exit ATM',
    comentario: ' '
  },
  {
    causalidad: 'Error Operativo - TDV deja segundo recibo de contadores',
    tipoSR: 'CHGC',
    codigoEntorno: '19NS',
    codigoReparacion: '03',
    categoria: '1B',
    mayor: '7C',
    menor: 'S5',
    description: 'Replenisher Improper Operation /Exit ATM',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Error Operativo - TDV no borra contadores',
    tipoSR: 'CHGC',
    codigoEntorno: '19N8',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: '7C',
    menor: 'S5',
    description: 'Counters Not Cleared',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Error Operativo - Fascia dejada sin asegurar',
    tipoSR: 'CHGC',
    codigoEntorno: '19KV',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: '36',
    menor: 'W3',
    description: 'Cabinet Left Unsecured',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Error Usuario final - Efectivo depositado en Multifuncional de Mala calidad',
    tipoSR: 'CHGC',
    codigoEntorno: '19KO',
    codigoReparacion: 'XX',
    categoria: '1B',
    mayor: 'SD',
    menor: 'TJ',
    description: 'Deposited Cash Poor Quality',
    comentario: ' '
  },
  {
    causalidad: 'Gaveta dañada por manipulacion generando fallas',
    tipoSR: 'CHGC',
    codigoEntorno: '19N2',
    codigoReparacion: '59',
    categoria: '1B',
    mayor: 'ND',
    menor: 'CC',
    description: 'Cassette Not',
    comentario: ''
  },
  {
    causalidad: 'Incumplimiento TDV No llego',
    tipoSR: 'CHGC',
    codigoEntorno: '19K8',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: '36',
    menor: 'W3',
    description: 'Vendor Meet',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Mantenimiento Preventivo Fallido restriccion de ingreso',
    tipoSR: 'PM',
    codigoEntorno: '0',
    codigoReparacion: 'O',
    categoria: '1B',
    mayor: 'O',
    menor: 'O',
    description: '',
    comentario: 'Se cierra como PM'
  },
  {
    causalidad: 'Mantenimiento Preventivo Fallido no entulado - visita fallida',
    tipoSR: 'PM',
    codigoEntorno: '0',
    codigoReparacion: '0',
    categoria: '1B',
    mayor: '0',
    menor: '0',
    description: '',
    comentario: 'Se cierra como PM'
  },
  {
    causalidad: 'Problema Aire Acondicionado en afectacion al ATM',
    tipoSR: 'CHGC',
    codigoEntorno: '19KT',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: '36',
    menor: 'W3',
    description: 'Temperature / Humidity',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Problema Aire Acondicionado en afectacion al ATM con cambio de partes ATM',
    tipoSR: 'CHGC',
    codigoEntorno: '19KT',
    codigoReparacion: '11',
    categoria: '1B',
    mayor: 'XX',
    menor: 'XX',
    description: 'Temperature / Humidity',
    comentario: ' '
  },
  {
    causalidad: 'Problema comunicaciones o equipos comunicaciones o proveedor de comunicaciones no llego',
    tipoSR: 'CHGC',
    codigoEntorno: '19KQ',
    codigoReparacion: '57',
    categoria: '1B',
    mayor: 'PN',
    menor: 'D4',
    description: ' Network/Switch (Non-Ncr)',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Problema electrico - No hay Fluido electrico',
    tipoSR: 'CHGC',
    codigoEntorno: '19K4',
    codigoReparacion: '47',
    categoria: '1B',
    mayor: 'CH',
    menor: 'LA',
    description: ' Bad/No Power or ATM',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Problema electrico - Voltajes altos',
    tipoSR: 'CHGC',
    codigoEntorno: '19K4',
    codigoReparacion: 'XX',
    categoria: '1B',
    mayor: 'CH',
    menor: 'LA',
    description: 'Bad/No Power or ATM',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Problema electrico - Problema UPS',
    tipoSR: 'CHGC',
    codigoEntorno: '19K4',
    codigoReparacion: '47',
    categoria: '1B',
    mayor: 'PN',
    menor: 'D9',
    description: 'Bad/No Power or ATM',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Problema ó Reinstalacion Software Cliente',
    tipoSR: 'CHGC',
    codigoEntorno: '19KP',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: 'CH',
    menor: 'X1',
    description: 'Non-Ncr Sw / Hw Error',
    comentario: ' '
  },
  {
    causalidad: 'Reinstalacion Software SIN Falla del ATM ',
    tipoSR: 'CHGC',
    codigoEntorno: '19KP',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: 'CH',
    menor: 'X1',
    description: 'Non-Ncr Sw / Hw Error',
    comentario: ' '
  },
  {
    causalidad: 'Restriccion de Site - No acceso al ATM para NCR ',
    tipoSR: 'CHGC',
    codigoEntorno: '19KL',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: '36',
    menor: 'W3',
    description: 'No Access',
    comentario: ' '
  },
  {
    causalidad: 'Restriccion de Site - No hay clave de alarma Site - NO se pudo abrir cofre',
    tipoSR: 'CHGC',
    codigoEntorno: '19KL',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: '36',
    menor: 'W3',
    description: 'No Access',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'ACL, acciones de recuparaciones remotas o monitoreo del banco',
    tipoSR: 'CHGC',
    codigoEntorno: '19NR',
    codigoReparacion: '51',
    categoria: '1B',
    mayor: '50',
    menor: 'XB',
    description: 'Other See Comments',
    comentario: ' '
  },
  {
    causalidad: 'Se encontro ATM sin falla',
    tipoSR: 'CHGC',
    codigoEntorno: '19KR',
    codigoReparacion: '53',
    categoria: '1B',
    mayor: '36',
    menor: 'W3',
    description: 'No Fault Found (Nff)',
    comentario: 'Si es reporte de FLM se cierra CHGF y si es de segunda linea se cierra CHGC'
  },
  {
    causalidad: 'Se encontro ATM sin falla - se corren diagnosticos  y validacion de funcionamiento ',
    tipoSR: 'CHGC',
    codigoEntorno: '19KR',
    codigoReparacion: '53',
    categoria: '1B',
    mayor: '36',
    menor: 'W3',
    description: 'No Fault Found (Nff)',
    comentario: ' '
  },
  {
    causalidad: 'Vandalismo Mayor',
    tipoSR: 'CHGC',
    codigoEntorno: '19NP',
    codigoReparacion: 'XX',
    categoria: '1B',
    mayor: 'XX',
    menor: 'XX',
    description: 'Damage/Vandalism/Tampering',
    comentario: ' '
  },
  {
    causalidad: 'Vandalismo Mayor Impresora cambio de parte por manipulacion',
    tipoSR: 'CHGC',
    codigoEntorno: '19NP',
    codigoReparacion: '11',
    categoria: '1B',
    mayor: '7C',
    menor: 'S5',
    description: 'Damage/Vandalism/Tampering',
    comentario: ' '
  },
  {
    causalidad: 'Vandalismo Menor Lectora sin cambio ni desmonte- reparacion Kit de Limpieza',
    tipoSR: 'CHGC',
    codigoEntorno: '19NP',
    codigoReparacion: '48',
    categoria: '1B',
    mayor: '72',
    menor: 'YC',
    description: 'Damage/Vandalism/Tampering',
    comentario: ' '
  },
  {
    causalidad: 'Vandalismo Menor',
    tipoSR: 'CHGC',
    codigoEntorno: '19NP',
    codigoReparacion: '48',
    categoria: '1B',
    mayor: 'XX',
    menor: 'XX',
    description: 'Damage/Vandalism/Tampering',
    comentario: ' '
  },
  {
    causalidad: 'Vandalismo Menor "PARA SANTANDER"',
    tipoSR: 'CHGC',
    codigoEntorno: '19NP',
    codigoReparacion: '48',
    categoria: '1B',
    mayor: 'XX',
    menor: 'XX',
    description: 'Damage/Vandalism/Tampering',
    comentario: ' '
  },
];

console.log(datos.length);
